name: buildspec Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:   
      - uses: actions/checkout@v3
      - name: Setup Dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'  
      - name: Install dependencies
        run: dotnet restore IrisBack/Iris/Iris.csproj
      - name: Build
        run: dotnet build IrisBack/Iris/Iris.csproj --configuration Release --no-restore
      
      - name: Checkout repo
        uses: actions/checkout@v3       
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2      
                       
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push docker image to Amazon ECR        
        run: |
          docker build -f IrisBack/Iris/Dockerfile -t 120311526263.dkr.ecr.us-east-2.amazonaws.com/iris .
          docker push 120311526263.dkr.ecr.us-east-2.amazonaws.com/iris

      - name: Deploy to Elastic Beanstalk
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-2'  # Cambia esto a tu región de AWS
          APPLICATION_NAME: 'iris-todo'  # Cambia esto al nombre de tu aplicación en Elastic Beanstalk
          ENVIRONMENT_NAME: 'iris-todo-env'  # Cambia esto al nombre de tu entorno en Elastic Beanstalk
        run: |
          aws elasticbeanstalk create-application-version --application-name $APPLICATION_NAME --version-label $GITHUB_SHA --source-bundle S3Bucket=$APPLICATION_NAME,S3Key=deploy.zip
          aws elasticbeanstalk update-environment --environment-name $ENVIRONMENT_NAME --version-label $GITHUB_SHA
    
    
      
      
      
